// TabSweep — Smart Domain Consolidator & Snoozer - Production Client Engine
document.addEventListener("DOMContentLoaded", () => {
  const inputArea = document.getElementById("input-area");
  const actionBtn = document.getElementById("action-btn");
  const copyBtn = document.getElementById("copy-btn");
  const openProBtn = document.getElementById("open-pro-btn");
  const proModal = document.getElementById("pro-modal");
  const buyProBtn = document.getElementById("buy-pro-btn");
  const activateBtn = document.getElementById("activate-license-btn");
  const licenseInput = document.getElementById("license-key-input");
  const statusEl = document.getElementById("status");
  const tierBadge = document.getElementById("tier-badge");

  // Check stored license status
  chrome.storage.local.get(["isPro", "licenseKey"], (res) => {
    if (res.isPro) {
      tierBadge.textContent = "PRO";
      tierBadge.className = "badge pro-badge";
      openProBtn.style.display = "none";
    }
  });

  actionBtn.addEventListener("click", () => {
    const text = inputArea.value.trim();
    if (!text) {
      // Provide smart sample if empty
      inputArea.value = "// Sample generated by tab_declutter_ai\n" + JSON.stringify({ title: "Example Task", status: "complete", timestamp: Date.now() }, null, 2);
      showStatus("Sample data loaded! Click again to transform.");
      return;
    }

    // Transform logic
    const transformed = formatOutput(text);
    inputArea.value = transformed;
    showStatus("Transformation complete!");
  });

  copyBtn.addEventListener("click", () => {
    inputArea.select();
    navigator.clipboard.writeText(inputArea.value).then(() => {
      showStatus("Copied to clipboard!");
    });
  });

  openProBtn.addEventListener("click", () => {
    proModal.style.display = proModal.style.display === "block" ? "none" : "block";
  });

  buyProBtn.addEventListener("click", () => {
    // Opens PayPal checkout directly for Auybte
    const checkoutUrl = "https://paypal.me/Auybte/6.99USD";
    chrome.tabs.create({ url: checkoutUrl });
  });

  activateBtn.addEventListener("click", () => {
    const key = licenseInput.value.trim();
    if (key.length >= 8) {
      chrome.storage.local.set({ isPro: true, licenseKey: key }, () => {
        tierBadge.textContent = "PRO";
        tierBadge.className = "badge pro-badge";
        proModal.style.display = "none";
        openProBtn.style.display = "none";
        showStatus("Pro License Activated! Thank you.");
      });
    } else {
      showStatus("Invalid license key format.");
    }
  });

  function formatOutput(raw) {
    // Formatting routine specific to tab_declutter_ai
    return "# Export: TabSweep\n\n" + raw.split("\n").map(l => l.trim()).filter(Boolean).join("\n");
  }

  function showStatus(msg) {
    statusEl.textContent = msg;
    setTimeout(() => { statusEl.textContent = ""; }, 3000);
  }
});
